name: 1.3.2 Скрипт проверки на устройстве
on:
  push:
  workflow_dispatch:

jobs:
  check:
    uses: ant-lab-ru/es-test/.github/workflows/check-1-3-2.yml@master
    secrets:
      ES_ACCOUNT_SECRET: ${{ secrets.ES_ACCOUNT_SECRET }}
