name: 1.2.3 Программное избавление от дребезга
on:
  push:
  workflow_dispatch:

jobs:
  check:
    uses: ant-lab-ru/es-test/.github/workflows/check-1-2-3.yml@master
    secrets:
      ES_ACCOUNT_SECRET: ${{ secrets.ES_ACCOUNT_SECRET }}
